### ISSUE TITLE
Create 'Diabetes in children' page.

### ISSUE THREAD

**Issue by boradesanket13** [Sanket1308/Diabetes-prediction-webapp#8] opened 2022-12-07 10:32 UTC

**Comment by guptamanas7** [comment] 2022-12-23 15:12
If you are looking for a page that consists of all the aspects of Diabetes in children, like the causes, symptoms, precautions, and solutions, then I am up to contribute to this issue. Please assign this to me.

**Closed as completed** 2022-12-31 15:14 UTC
Labels: Codepeak 2022, Hard
